### PR TITLE
Attribute ranges

### PR DESCRIPTION
**Pull request by JeppeLindberg**

### CODE REVIEW

**Review by LivHolm — CHANGES_REQUESTED** [review]
Include a URL of where to get the kaggle dataset in the README.md file, and info about the test_config

**Review by LivHolm — CHANGES_REQUESTED** [review]
Delete mock_data.py and spotify_request.py since they aren't used.

**Review by LivHolm — CHANGES_REQUESTED** [review]
test in the test_range_recommender fails

**Review by LivHolm — APPROVED** [review]

**Comment by ProgDaniel** [comment]
requirements.txt skal fyldes på med følgende packages

- numpy / numpy==1.22.3
- pandas / pandas==1.4.2

**Review by ProgDaniel — APPROVED** [review]
Good2Go

**Pull request merged**
